### PR TITLE
Allow local install

### PR DESCRIPTION
**Pull request by dadepo**
This change is to allow installing of jars into local maven repository. 

Doing:

`./gradlew install`

Will build and install into `.m2` 

I could not find a way to achieve the local installation with the current setup hence the modification.

I am not a gradle expert so I can't tell if this is the best approach to achieve this. So a review is appreciated.

### CODE REVIEW

**Comment by CerielJacobs** [comment]
There is, of course, “./gradlew installToMavenLocal”. Did this not work for you?

Best,	Ceriel

**Comment by dadepo** [comment]
Thanks for pointing that out. Did not take note of it!

**Comment by dadepo** [comment]
It seems not to work

> ./gradlew installToMavenLocal
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Task 'installToMavenLocal' not found in root project 'ipl'.
> 
> * Try:
> Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
> 

I also search the project for occurrence of `installToMavenLocal` but did not find any

**Comment by CerielJacobs** [comment]
Sorry, it is called publishToMavenLocal.

**Comment by dadepo** [comment]
Indeed. I can confirm that works! Thanks!

**Pull request closed without merging**
